name: Android Emulator CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify the distribution of Java to use
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'

      - name: Install Android SDK
        uses: android-emulator-runner/setup-android@v2
        with:
          sdk-version: '30' # Specify the Android SDK version you need
          emulator-version: '30' # Specify the Emulator version you need

      - name: Start emulator
        uses: android-emulator-runner/start-emulator@v2
        with:
          api-level: 30 # Specify the API level for the emulator
          emulator-type: 'pixel' # Specify the emulator type, e.g., 'pixel' or 'android'
          script: './gradlew connectedCheck' # Specify the script to run after emulator is booted

      - name: Wait for emulator to start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run tests
        run: ./gradlew connectedCheck

      - name: Stop emulator
        uses: android-emulator-runner/stop-emulator@v2
