name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./https://github.com/ST10254488/IMAD5112A1/tree/master/gradle/wrapper build

      - name: Run tests
        run: ./https://github.com/ST10254488/IMAD5112A1/tree/master/gradle/wrapper test
