name: Android Emulator CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android Emulator
        uses: actions/setup-android@v2
        with:
          sdk-version: '30' # Specify the Android SDK version you need
          emulator-type: 'pixel' # Specify the emulator type, e.g., 'pixel' or 'android'

      - name: Start Emulator
        run: emulator -avd pixel -no-audio -no-window

      - name: Wait for Emulator to Start
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: Run Tests
        run: ./gradlew test

      - name: Stop Emulator
        run: adb emu kill
